plugins: 
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}


publish_frequency: 1.0 # częstotliwość odświeżania WIDOKU mapy na ekranie

rolling_window: true # true -> mapa kosztów reprezentuje LOKALNE otoczenie wokół robota i przesuwa się razem z nim oraz jest aktualizowana na podstawie danych z sensorów
# wartośc true wynika z faktu, że lokalnie nie korzystamy z warstwy statycznej mapy budynku


robot_radius: 0.26 # wyznaczony w RViz opcją Measure d = 52 cm
obstacles: # źródło informacji o lokalnych przeszkodach --> LIDAR
    observation_sources: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: base_laser_link, clearing: true, marking: true, topic: /scan_raw}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  
  inflation_radius:     0.05